/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rudy
 */
public class Main extends javax.swing.JFrame {

    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SOAPbtn1 = new javax.swing.JButton();
        SOAPbtn2 = new javax.swing.JButton();
        JEBbtn1 = new javax.swing.JButton();
        JEBbtn2 = new javax.swing.JButton();
        RFbtn1 = new javax.swing.JButton();
        RFbtn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SOAPbtn1.setText("SOAP1");
        SOAPbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOAPbtn1ActionPerformed(evt);
            }
        });

        SOAPbtn2.setText("SOAP2");
        SOAPbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOAPbtn2ActionPerformed(evt);
            }
        });

        JEBbtn1.setText("JEB1");
        JEBbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEBbtn1ActionPerformed(evt);
            }
        });

        JEBbtn2.setText("JEB2");
        JEBbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEBbtn2ActionPerformed(evt);
            }
        });

        RFbtn1.setText("RESTFUL1");
        RFbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFbtn1ActionPerformed(evt);
            }
        });

        RFbtn2.setText("RESTFUL2");
        RFbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFbtn2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Elige uno a probar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RFbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RFbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JEBbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JEBbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SOAPbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SOAPbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SOAPbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(SOAPbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RFbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(RFbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JEBbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(JEBbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RFbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFbtn1ActionPerformed
        // TODO add your handling code here:
        dispose();
        RestFul1 RF1 = new RestFul1();
        RF1.setVisible(true);
        
      
       
    }//GEN-LAST:event_RFbtn1ActionPerformed

    private void RFbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFbtn2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Restful2 RF2 =new Restful2();
        RF2.setVisible(true);
    }//GEN-LAST:event_RFbtn2ActionPerformed

    private void JEBbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEBbtn1ActionPerformed
        // TOD
        dispose();
        JEB1 jeb1 = new JEB1();
        jeb1.setVisible(true);
    }//GEN-LAST:event_JEBbtn1ActionPerformed

    private void JEBbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEBbtn2ActionPerformed
        // TODO add your handling code here:
        dispose();
        JEB2 jeb2 =new JEB2();
        jeb2.setVisible(true);
    }//GEN-LAST:event_JEBbtn2ActionPerformed

    private void SOAPbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOAPbtn1ActionPerformed
        // TODO add your handling code here:
        dispose();
        SOAP1 soap1 = new SOAP1();
        soap1.setVisible(true);
    }//GEN-LAST:event_SOAPbtn1ActionPerformed

    private void SOAPbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOAPbtn2ActionPerformed
        // TODO add your handling code here:
        dispose();
        SOAP2 soap2= new SOAP2();
        soap2.setVisible(true);
    }//GEN-LAST:event_SOAPbtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JEBbtn1;
    private javax.swing.JButton JEBbtn2;
    private javax.swing.JButton RFbtn1;
    private javax.swing.JButton RFbtn2;
    private javax.swing.JButton SOAPbtn1;
    private javax.swing.JButton SOAPbtn2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
